all:
	$(MAKE) -C file  
	$(MAKE) -C tmessage  
	$(MAKE) -C tconfigmng  
	$(MAKE) -C tcan  
	$(MAKE) -C tnodenet
	
clean:
	$(MAKE) clean -C file  
	$(MAKE) clean -C tconfigmng  
	$(MAKE) clean -C tmessage  
	$(MAKE) clean -C tnodenet
	$(MAKE) clean -C tcan  